cryptokeepers2/Models/alert.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
namespace cryptokeepers2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alert
    {
        public int id { get; set; }
        public Nullable<byte> type { get; set; }
        [DisplayName("Wallet ID")]
        public string concern { get; set; }
        public Nullable<byte> flag { get; set; }
        public Nullable<byte> priority { get; set; }
        public Nullable<short> entity { get; set; }
        [DisplayName("Notes")]
        public string notes { get; set; }
        [DisplayName("Report Date")]
        public System.DateTime reported { get; set; }
        public Nullable<byte> coin { get; set; }
    
        public virtual coin coin1 { get; set; }
        public virtual entity entity1 { get; set; }
        public virtual flag flag1 { get; set; }
        public virtual priority priority1 { get; set; }
        public virtual type type1 { get; set; }
    }
}

cryptokeepers2/Controllers/alertsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cryptokeepers2.Models;

namespace cryptokeepers2.Controllers
{
    public class alertsController : Controller
    {
        private cryptokeepersdb1Entities1 db = new cryptokeepersdb1Entities1();

        // GET: alerts
        public ActionResult Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentFilter"] = searchString;
            var alerts = db.alerts.Include(a => a.coin1).Include(a => a.entity1).Include(a => a.flag1).Include(a => a.priority1).Include(a => a.type1);
            if (!String.IsNullOrEmpty(searchString))
            {
                alerts = alerts.Where(s => s.concern.Contains(searchString));
            }
 
        
            return View(alerts.ToList().OrderByDescending(m=>m.id));
        }

        // GET: alerts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alert alert = db.alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // GET: alerts/Create
        public ActionResult Create()
        {
            ViewBag.coin = new SelectList(db.coins, "id", "coinname");
            ViewBag.entity = new SelectList(db.entities, "id", "entityname");
            ViewBag.flag = new SelectList(db.flags, "id", "flagname");
            ViewBag.priority = new SelectList(db.priorities, "id", "priorityname");
            ViewBag.type = new SelectList(db.types, "id", "typename");
            return View();
        }

        // POST: alerts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,type,concern,flag,priority,entity,notes,reported,coin")] alert alert)
        {
            if (ModelState.IsValid)
            {
                db.alerts.Add(alert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            alert x = new alert();
            

            ViewBag.coin = new SelectList(db.coins, "id", "coinname", alert.coin);
            ViewBag.entity = new SelectList(db.entities, "id", "entityname", alert.entity);
            ViewBag.flag = new SelectList(db.flags, "id", "flagname", alert.flag);
            ViewBag.priority = new SelectList(db.priorities, "id", "priorityname", alert.priority);
            ViewBag.type = new SelectList(db.types, "id", "typename", alert.type);
            return View(alert);
        }

        // GET: alerts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alert alert = db.alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            ViewBag.coin = new SelectList(db.coins, "id", "coinname", alert.coin);
            ViewBag.entity = new SelectList(db.entities, "id", "entityname", alert.entity);
            ViewBag.flag = new SelectList(db.flags, "id", "flagname", alert.flag);
            ViewBag.priority = new SelectList(db.priorities, "id", "priorityname", alert.priority);
            ViewBag.type = new SelectList(db.types, "id", "typename", alert.type);
            return View(alert);
        }

        // POST: alerts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,type,concern,flag,priority,entity,notes,reported,coin")] alert alert)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.coin = new SelectList(db.coins, "id", "coinname", alert.coin);
            ViewBag.entity = new SelectList(db.entities, "id", "entityname", alert.entity);
            ViewBag.flag = new SelectList(db.flags, "id", "flagname", alert.flag);
            ViewBag.priority = new SelectList(db.priorities, "id", "priorityname", alert.priority);
            ViewBag.type = new SelectList(db.types, "id", "typename", alert.type);
            return View(alert);
        }

        // GET: alerts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            alert alert = db.alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // POST: alerts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            alert alert = db.alerts.Find(id);
            db.alerts.Remove(alert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cryptokeepers2/Views/alerts/Create.cshtml
@model cryptokeepers2.Models.alert

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>New Alert</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.type, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("type", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.concern, "Wallet ID or Address", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.concern, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.concern, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.coin, "Coin", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("coin", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.coin, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.flag, "Flag", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("flag", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.flag, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.priority, "Priority Level", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("priority", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.priority, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.entity, "Reporting Entity", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("entity", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.entity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.notes, "Notes/Details", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.reported, "Report date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.reported, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.reported, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cryptokeepers2/Views/alerts/Delete.cshtml
@model cryptokeepers2.Models.alert

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>alert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.concern)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.concern)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reported)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reported)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.coin1.coinname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.coin1.coinname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.entity1.entityname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.entity1.entityname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.flag1.flagname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.flag1.flagname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.priority1.priorityname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.priority1.priorityname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type1.typename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type1.typename)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

cryptokeepers2/Views/alerts/Details.cshtml
@model cryptokeepers2.Models.alert

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>alert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.concern)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.concern)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reported)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reported)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.coin1.coinname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.coin1.coinname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.entity1.entityname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.entity1.entityname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.flag1.flagname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.flag1.flagname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.priority1.priorityname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.priority1.priorityname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type1.typename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type1.typename)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

cryptokeepers2/Views/alerts/Edit.cshtml
@model cryptokeepers2.Models.alert

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>alert</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.type, "type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("type", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.concern, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.concern, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.concern, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.flag, "flag", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("flag", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.flag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.priority, "priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("priority", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.entity, "entity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("entity", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.entity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reported, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reported, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reported, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.coin, "coin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("coin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.coin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cryptokeepers2/Views/alerts/Index.cshtml
@model IEnumerable<cryptokeepers2.Models.alert>

@{
    ViewBag.Title = "Index";
    string Val = @DateTime.Now.ToShortDateString();
}

<h2>Index</h2>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a href=@Url.Action("Index","alerts")>Back to Full List</a>
        </p>
    </div>
</form>
<p>
    @Html.ActionLink("Create New", "Create")
    <button class="btn btn-default" onclick="exportTableToCSV('Report-@Val-.csv')">Download CSV</button>

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.concern)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.reported)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.coin1.coinname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.entity1.entityname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.flag1.flagname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.priority1.priorityname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type1.typename)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.concern)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reported)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.coin1.coinname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.entity1.entityname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.flag1.flagname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.priority1.priorityname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.type1.typename)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>